public class AlleAdresse
{
    public string LfdNr { get; set; }
    public string AdresseName1 { get; set; }
    public string AdresseName2 { get; set; }
    public string KlasseKlassenbezeichnung { get; set; }
    public string SchülerNachname { get; set; }
    public string SchülerVorname { get; set; }
    public string AdresseAusweisnummer { get; set; }
    public string AdresseDatumAustritt { get; set; }
    public string AdresseDatumEintritt { get; set; }
    public string AdresseDatumGeburt { get; set; }
    public string AdresseEmail { get; set; }
    public string AdresseEmailKomplett { get; set; }
    public string AdresseFamilienstand { get; set; }
    public string AdresseExterneID { get; set; }
    public string AdresseOrt { get; set; }
    public string AdressePlz { get; set; }
    public string AdressePostfachPlz { get; set; }
    public string AdressePostfach { get; set; }
    public string AdresseSorgeberechtigtJN { get; set; }
    public string AdresseSprache { get; set; }
    public string AdresseStaat { get; set; }
    public string AdresseStraße { get; set; }
    public string AdresseTelefon1 { get; set; }
    public string AdresseTelefon2 { get; set; }
    public string AdresseTelefon3 { get; set; }
    public string AdresseTitel { get; set; }
    public string AdresseTypAdresse { get; set; }
    public string AdresseTypMitglied { get; set; }
    public string AdresseTypTelefon1 { get; set; }
    public string AdresseTypTelefon2 { get; set; }
    public string AdresseTypTelefon3 { get; set; }
    public string BetriebAnrede { get; set; }
    public string BetriebAnredetext { get; set; }
    public string BetriebAnsprechpartner { get; set; }
    public string BetriebAusbilderAbwVomAnsprPartner { get; set; }
    public string BetriebBetriebenummer { get; set; }
    public string BetriebEmailAdresse { get; set; }
    public string BetriebBriefadresse { get; set; }
    public string BetriebName1 { get; set; }
    public string BetriebName2 { get; set; }
    public string BetriebOrt { get; set; }
    public string BetriebOrtsteil { get; set; }
    public string BetriebPlz { get; set; }
    public string BetriebStraße { get; set; }
    public string BetriebTelefon1 { get; set; }
    public string BetriebTelefon2 { get; set; }
    public string KlasseBereich { get; set; }
    public string SchülerGeburtsdatum { get; set; }
    public string SchülerGeburtsname { get; set; }
    public string SchülerGeburtsort { get; set; }
    public string SchülerGeschlecht { get; set; }
    public string SchülerGeschlechtAuflösung { get; set; }
    public string SchülerNameElternteil { get; set; }
    public string SchülerNummer { get; set; }
    public string SchülerStaat { get; set; }
    public string SchülerStaatAuflösung { get; set; }
    public string SchülerMuttersprache { get; set; }
    public string SchülerMutterspracheAuflösung { get; set; }
    public string SchülerVolljährigJN { get; set; }
    public string SchülerVorgangSchuljahr { get; set; }
    public string SchülerAnrede { get; set; }
    public string SchülerAnredeAuflösung { get; set; }
    public string SchülerAnredeAnredetext { get; set; }
}
