public class AlleAdresse
{
    public string LfdNr { get; set; }
    public string Nachname { get; set; }
    public string Name2DerAdresse { get; set; }
    public string Name3DerAdresse { get; set; }
    public string GebäudeOrt { get; set; }
    public string GebäudePlz { get; set; }
    public string GebäudeStraße { get; set; }
    public string Abrechnungsmodus { get; set; }
    public string Abteilung { get; set; }
    public string AdresseQuellKennzeichen { get; set; }
    public string AdresseKategorien { get; set; }
    public string AdresseBerufLangtext { get; set; }
    public string Adresstyp { get; set; }
    public string AkadTitel { get; set; }
    public string Aktiv { get; set; }
    public string AnredeAuflösung { get; set; }
    public string Anredeform { get; set; }
    public string Anredetext { get; set; }
    public string Ansprechpartner { get; set; }
    public string AnzahlKopien { get; set; }
    public string Arbeitgeber { get; set; }
    public string ArtDerKommunikation { get; set; }
    public string ArtDerKommunikationAuflösung { get; set; }
    public string ArtDerLastschriftausführungSEPA { get; set; }
    public string Austrittsdatum { get; set; }
    public string Ausweisnummer { get; set; }
    public string Ausweisnummer2 { get; set; }
    public string Ausweisnummer3 { get; set; }
    public string Ausweisnummer4 { get; set; }
    public string Belegdruck { get; set; }
    public string BemerkungZurAdresse { get; set; }
    public string Beruf { get; set; }
    public string Briefadresse { get; set; }
    public string DatumDerErteilungDesSEPAMandats { get; set; }
    public string DatumErsteBuchung { get; set; }
    public string DatumLetzteBuchung { get; set; }
    public string DebitorSaldo { get; set; }
    public string DebitorGruppe { get; set; }
    public string DebitorDebitornummer { get; set; }
    public string EmailKomplett { get; set; }
    public string EmailVertraulich { get; set; }
    public string EmailAdresse { get; set; }
    public string EmailVersandAktiv { get; set; }
    public string Eintrittsdatum { get; set; }
    public string ExterneID { get; set; }
    public string Familienstand { get; set; }
    public string Geburtsdatum { get; set; }
    public string Gehalt { get; set; }
    public string Gemeindekennzeichen { get; set; }
    public string Hausnummer { get; set; }
    public string Herkunftsland { get; set; }
    public string HomepageURL { get; set; }
    public string IBAN { get; set; }
    public string Kalenderjahr { get; set; }
    public string KennzeichenDerHauptadresse { get; set; }
    public string Kontakt1JN { get; set; }
    public string Kontakt2JN { get; set; }
    public string Kontakt3JN { get; set; }
    public string Kontoinhaber { get; set; }
    public string Korrespondenzsprache { get; set; }
    public string LehrerSuchbegriff { get; set; }
    public string Länderkennzeichen { get; set; }
    public string Mahnkennzeichen { get; set; }
    public string Mitgliedstyp { get; set; }
    public string NameDesBankinstituts { get; set; }
    public string NummerFürSMSVersand { get; set; }
    public string NächstRechStellung { get; set; }
    public string Ortsteil { get; set; }
    public string Personalausweisnummer { get; set; }
    public string Postfach { get; set; }
    public string PostleitzahlDerPostfachadresse { get; set; }
    public string Rechnungsrythmus { get; set; }
    public string SaldoAktuellZum { get; set; }
    public string SchuleAmtlicheBezeichnung1 { get; set; }
    public string SchuleAmtlicheBezeichnung2 { get; set; }
    public string SchuleAmtlicheBezeichnung3 { get; set; }
    public string SchuleEmailAdresse { get; set; }
    public string SchuleGenitivName { get; set; }
    public string SchuleGläubigerIdentifikationsnummer { get; set; }
    public string SchuleHomepage { get; set; }
    public string SchuleOrt { get; set; }
    public string SchuleOrtsteil { get; set; }
    public string SchulePlz { get; set; }
    public string SchuleSchulartAuflösung { get; set; }
    public string SchuleSchulname { get; set; }
    public string SchuleSchulname2 { get; set; }
    public string SchuleSchulname3 { get; set; }
    public string SchuleSchulnummer { get; set; }
    public string SchuleStraße { get; set; }
    public string SchuleTelefax { get; set; }
    public string SchuleTelefon1 { get; set; }
    public string SchuleTelefon2 { get; set; }
    public string SchuleZeugniskopfzeile1 { get; set; }
    public string SchuleZeugniskopfzeile2 { get; set; }
    public string SchuleZeugniskopfzeile3 { get; set; }
    public string SchülerAnrede { get; set; }
    public string SchülerAusgetretenJN { get; set; }
    public string SchülerBekenntnis { get; set; }
    public string SchülerGeschlecht { get; set; }
    public string SchülerNachname { get; set; }
    public string SchülerVolljährigJN { get; set; }
    public string SchülerVorgangSchuljahr { get; set; }
    public string SchülerVorname { get; set; }
    public string SchülerWird16Am { get; set; }
    public string SchülerWird18Am { get; set; }
    public string SorgeberechtigungJN { get; set; }
    public string SorgeberechtigungTyp { get; set; }
    public string SozialversNr { get; set; }
    public string Staatsangehörigkeit { get; set; }
    public string SwiftBICCode { get; set; }
    public string Telefax { get; set; }
    public string Telefon1 { get; set; }
    public string Telefon1Typ { get; set; }
    public string Telefon2 { get; set; }
    public string Telefon2Typ { get; set; }
    public string Telefon3 { get; set; }
    public string Telefon3Typ { get; set; }
    public string Telefon4 { get; set; }
    public string Telefon4Typ { get; set; }
    public string TextfeldAuszubildendeR { get; set; }
    public string TextfeldDemDerGroß { get; set; }
    public string TextfeldDemDerKlein { get; set; }
    public string TextfeldDenDieGroß { get; set; }
    public string TextfeldDenDieKlein { get; set; }
    public string TextfeldDerDieGroß { get; set; }
    public string TextfeldDerDieKlein { get; set; }
    public string TextfeldDesSchülersDerSchülerin { get; set; }
    public string TextfeldDesDerGroß { get; set; }
    public string TextfeldDesDerKlein { get; set; }
    public string TextfeldErSieGroß { get; set; }
    public string TextfeldErSieKlein { get; set; }
    public string TextfeldHerrFrau { get; set; }
    public string TextfeldIhrSohnIhreTochter { get; set; }
    public string TextfeldIhrIhreGroß { get; set; }
    public string TextfeldIhrIhreKlein { get; set; }
    public string TextfeldIhremSohnIhrerTochter { get; set; }
    public string TextfeldIhrenSohnIhreTochter { get; set; }
    public string TextfeldIhresSohnesIhrerTochter { get; set; }
    public string TextfeldJungeMädchen { get; set; }
    public string TextfeldSchülerIn { get; set; }
    public string TextfeldSeinIhrGroß { get; set; }
    public string TextfeldSeinIhrKlein { get; set; }
    public string TextfeldSeineIhreGroß { get; set; }
    public string TextfeldSeineIhreKlein { get; set; }
    public string TextfeldSeinemIhremGroß { get; set; }
    public string TextfeldSeinemIhremKlein { get; set; }
    public string TextfeldSeinerIhrerGroß { get; set; }
    public string TextfeldSeinerIhrerKlein { get; set; }
    public string TextfeldSeinesIhresGroß { get; set; }
    public string TextfeldSeinesIhresKlein { get; set; }
    public string TextfeldSohnTochter { get; set; }
    public string SchülerTypDerAdresse { get; set; }
    public string TypDTAUSVerfahren { get; set; }
    public string VerkehrsMuttersprache { get; set; }
    public string Vorlagensprache { get; set; }
    public string ZahlVerkehrGutschrift { get; set; }
    public string ZahlungsplanErwünscht { get; set; }
    public string Zahlungsverkehr { get; set; }
    public string Zahlweise { get; set; }
    public string ZeigerAufAdressentabelle { get; set; }
    public string ZeigerAufBetriebesatz { get; set; }
    public string ZeigerAufGebäudesatz { get; set; }
    public string ZeigerAufHeimBT { get; set; }
    public string ZeigerAufLaufbahnsatz { get; set; }
    public string ZeigerAufLehrerstammsatz { get; set; }
    public string ZeigerAufSchulensatz { get; set; }
    public string ZeigerAufSchülersatz { get; set; }
    public string ZeigerAufStammIDAdresse { get; set; }
    public string ZeigerAufStammIDAdresse2 { get; set; }
    public string ZeigerAufStammIDAdresse3 { get; set; }
    public string ZeigerAufStammIDAdresse4 { get; set; }
    public string ZeigerAufStammIDAdresse5 { get; set; }
    public string ZeigerAufStammIDAdresse6 { get; set; }
    public string ZeigerAufStammIDAdresse7 { get; set; }
    public string ZeigerAufStammIDAdresse8 { get; set; }
    public string ZeigerAufStammIDAdresse9 { get; set; }
    public string ZeigerAufStammIDAdresse10 { get; set; }
    public string ZeigerAufStammIDAdresse11 { get; set; }
    public string ZeigerAufStammIDAdresse12 { get; set; }
    public string ZeigerAufStammIDAdresse13 { get; set; }
    public string ZeigerAufStammIDAdresse14 { get; set; }
    public string ZeigerAufStammIDAdresse15 { get; set; }
    public string ZeigerAufStammIDAdresse16 { get; set; }
    public string ZeigerAufStammIDAdresse17 { get; set; }
    public string ZeigerAufStammIDAdresse18 { get; set; }
    public string ZeigerAufStammIDAdresse19 { get; set; }
    public string ZeigerAufStammIDAdresse20 { get; set; }
    public string ZeigerAufStammIDAdresse21 { get; set; }
    public string ZeigerAufStammIDAdresse22 { get; set; }
    public string ZeigerAufStammIDAdresse23 { get; set; }
    public string ZeigerAufStammIDAdresse24 { get; set; }
    public string ZeigerAufStammIDAdresse25 { get; set; }
    public string ZeigerAufStammIDAdresse26 { get; set; }
    public string ZeigerAufStammIDAdresse27 { get; set; }
    public string ZeigerAufStammIDAdresse28 { get; set; }
    public string ZeigerAufStammIDAdresse29 { get; set; }
    public string ZeigerAufStammIDAdresse30 { get; set; }
    public string ZeigerAufStammIDAdresse31 { get; set; }
    public string ZeigerAufStammIDAdresse32 { get; set; }
    public string ZeigerAufStammIDAdresse33 { get; set; }
    public string ZeigerAufStammIDAdresse34 { get; set; }
    public string ZeigerAufStammIDAdresse35 { get; set; }
    public string ZeigerAufStammIDAdresse36 { get; set; }
    public string ZeigerAufStammIDAdresse37 { get; set; }
    public string ZeigerAufStammIDAdresse38 { get; set; }
    public string ZeigerAufStammIDAdresse39 { get; set; }
    public string ZeigerAufStammIDAdresse40 { get; set; }
    public string ZeigerAufStammIDAdresse41 { get; set; }
    public string ZeigerAufStammIDAdresse42 { get; set; }
    public string ZeigerAufStammIDAdresse43 { get; set; }
    public string ZeigerAufStammIDAdresse44 { get; set; }
    public string ZeigerAufStammIDAdresse45 { get; set; }
    public string ZeigerAufStammIDAdresse46 { get; set; }
    public string ZeigerAufStammIDAdresse47 { get; set; }
    public string ZeigerAufStammIDAdresse48 { get; set; }
    public string ZeigerAufStammIDAdresse49 { get; set; }
    public string ZeigerAufStammIDAdresse50 { get; set; }
    public string SchuelerTypDerAdresse { get; set; }
    public string ZahlungsplanErwuenscht { get; set; }
    public string ZeigerAufGebaeudesatz { get; set; }
    public string ZeigerAufSchuelersatz { get; set; }
    public string ZeigerAufStammIDBetrieb { get; set; }
    public string ZeigerAufStammIDLehrer { get; set; }
    public string ZeigerAufStammIDSchule { get; set; }
    public string ZeigerAufStammIDSchueler { get; set; }
    public string ZeigerAufVertragssatz { get; set; }
    public string ZeitstempelLetzteAenderung { get; set; }
    public string TextfeldAuszubildende { get; set; }
    
}