public class SchuelerBasisdatum
{
    public string Nachname { get; set; }
    public string Vorname { get; set; }
    public string Geburtsdatum { get; set; }
    public string Geschlecht { get; set; }
    public string Status { get; set; }
    public string PLZ { get; set; }
    public string Ort { get; set; }
    public string Straße { get; set; }
    public string Aussiedler { get; set; }
    public string Staatsangehörigkeit1 { get; set; }
    public string Konfession { get; set; }
    public string StatistikKrzKonfession { get; set; }
    public string Aufnahmedatum { get; set; }
    public string AbmeldedatumReligionsunterricht { get; set; }
    public string AnmeldedatumReligionsunterricht { get; set; }
    public string SchulpflichtErfüllt { get; set; }
    public string ReformPädagogik { get; set; }
    public string NrStammschule { get; set; }
    public string Jahr { get; set; }
    public string Abschnitt { get; set; }
    public string Jahrgang { get; set; }
    public string Klasse { get; set; }
    public string Schulgliederung { get; set; }
    public string OrgForm { get; set; }
    public string Klassenart { get; set; }
    public string Fachklasse { get; set; }
    public string NochFrei { get; set; }
    public string VerpflichtungSprachförderkurs { get; set; }
    public string TeilnahmeSprachförderkurs { get; set; }
    public string Einschulungsjahr { get; set; }
    public string ÜbergangsempfJG5 { get; set; }
    public string JahrWechselS1 { get; set; }
    public string SchulformS1 { get; set; }
    public string JahrWechselS2 { get; set; }
    public string Förderschwerpunkt { get; set; }
    public string Förderschwerpunkt2 { get; set; }
    public string Schwerstbehinderung { get; set; }
    public string Autist { get; set; }
    public string LSSchulnr { get; set; }
    public string LSSchulform { get; set; }
    public string Herkunft { get; set; }
    public string LSEntlassdatum { get; set; }
    public string LSJahrgang { get; set; }
    public string LSVersetzung { get; set; }
    public string LSReformpädagogik { get; set; }
    public string LSGliederung { get; set; }
    public string LSFachklasse { get; set; }
    public string LSAbschluss { get; set; }
    public string Abschluss { get; set; }
    public string SchulnrNeueSchule { get; set; }
    public string Zuzugsjahr { get; set; }
    public string GeburtslandSchüler { get; set; }
    public string GeburtslandMutter { get; set; }
    public string GeburtslandVater { get; set; }
    public string Verkehrssprache { get; set; }
    public string DauerKindergartenbesuch { get; set; }
}
