public class Sim
{
    public string Familienname { get; set; }
    public string Vorname { get; set; }
    public string Austritt { get; set; }
    public string SchülerLeJahrDa { get; set; }
    public string SchülerBerufswechsel { get; set; }
    public string VorjahrC05AktjahrC06 { get; set; }
    public string Bezugsjahr1 { get; set; }
    public string Status2 { get; set; }
    public string Lfdnr3 { get; set; }
    public string Klasse4 { get; set; }
    public string Gliederung5 { get; set; }
    public string Fachklasse6 { get; set; }
    public string Klassenart7 { get; set; }
    public string Orgform8 { get; set; }
    public string Aktjahrgang9 { get; set; }
    public string Foerderschwerp10 { get; set; }
    public string Schwerstbehindert11 { get; set; }
    public string Reformpdg12 { get; set; }
    public string Jva13 { get; set; }
    public string Plz14 { get; set; }
    public string Ort15 { get; set; }
    public string Gebdat16 { get; set; }
    public string Geschlecht17 { get; set; }
    public string Staatsang18 { get; set; }
    public string Religion19 { get; set; }
    public string Relianmeldung20 { get; set; }
    public string Reliabmeldung21 { get; set; }
    public string Aufnahmedatum22 { get; set; }
    public string Labk23 { get; set; }
    public string Ausbildort24 { get; set; }
    public string Betriebsort25 { get; set; }
    public string LSSchulform26 { get; set; }
    public string Lsschulnummer27 { get; set; }
    public string LSGliederung28 { get; set; }
    public string LSFachklasse29 { get; set; }
    public string Lsklassenart30 { get; set; }
    public string Lsreformpdg31 { get; set; }
    public string LSSschulentl32 { get; set; }
    public string LSJahrgang33 { get; set; }
    public string LSQual34 { get; set; }
    public string Lsversetz35 { get; set; }
    public string VOKlasse36 { get; set; }
    public string VOGliederung37 { get; set; }
    public string VOFachklasse38 { get; set; }
    public string VOOrgform39 { get; set; }
    public string VOKlassenart40 { get; set; }
    public string VOJahrgang41 { get; set; }
    public string VOFoerderschwerp42 { get; set; }
    public string VOSchwerstbehindert43 { get; set; }
    public string VOReformpdg44 { get; set; }
    public string EntlDatum45 { get; set; }
    public string Zeugnis46 { get; set; }
    public string Schulpflichterf47 { get; set; }
    public string Schulwechselform48 { get; set; }
    public string Versetzung49 { get; set; }
    public string JahrZuzug50 { get; set; }
    public string JahrEinschulung51 { get; set; }
    public string JahrSchulwechsel52 { get; set; }
    public string Zugezogen53 { get; set; }
    public string GebLandMutter54 { get; set; }
    public string GebLandVater55 { get; set; }
    public string ElternteilZugezogen56 { get; set; }
    public string Verkehrssprache57 { get; set; }
    public string Einschulungsart58 { get; set; }
    public string GSEmpfehlung59 { get; set; }
    public string Massnahmetraeger60 { get; set; }
    public string Betreuung61 { get; set; }
    public string BKAZVO62 { get; set; }
    public string Foerderschwerpunkt263 { get; set; }
    public string VOFoerderschwerpunkt264 { get; set; }
    public string Berufsabschluss65 { get; set; }
    public string Produktname66 { get; set; }
    public string Produktversion67 { get; set; }
    public string Adressmerkmal68 { get; set; }
    public string Internatsplatz69 { get; set; }
    public string Koopklasse70 { get; set; }
}